ALTER TABLE MATCHED_SERIES
    RENAME TO SERIES_THUMBNAILS;

ALTER TABLE MATCHED_BOOKS
    RENAME TO BOOK_THUMBNAILS;


CREATE TABLE SERIES_MATCH
(
    SERIES_ID          varchar NOT NULL,
    TYPE               varchar NOT NULL,
    SERVER_TYPE        varchar NOT NULL,
    PROVIDER           varchar NOT NULL,
    PROVIDER_SERIES_ID varchar NOT NULL,
    EDITION            varchar,
    PRIMARY KEY (SERIES_ID, SERVER_TYPE)
);
